const categories=[['all','All pieces','crop-1'],['seating','Seating','crop-1'],['lighting','Lighting','crop-2'],['tabletop','Tabletop','crop-3'],['textiles','Textiles','crop-4'],['storage','Storage','crop-5']];
const names={seating:['Arc Lounge Chair','Lowline Reading Chair','Pebble Occasional Seat','Morrow Dining Chair','Cloud Bench','Cove Armchair','Felt Lounge Stool','Serein Daybed','Dune Club Chair','Plinth Seat'],lighting:['Orlo Pendant','Halo Table Lamp','Vela Floor Light','Forma Wall Sconce','Noma Desk Light','Lune Pendant','Mica Lantern','Arc Rail Light','Sola Reading Lamp','Taper Candle Light'],tabletop:['Silt Side Table','Pillar Travertine Table','Mesa Coffee Table','Onda Serving Bowl','Ridge Stone Tray','Contour Plinth','Mori Ceramic Set','Caldera Dining Table','Loom Side Table','Still Water Carafe'],textiles:['Washed Linen Throw','Oat Cloud Cushion','Clay Stripe Blanket','Dawn Linen Sheet','Soft Form Cushion','Hearth Wool Rug','Quiet Cotton Robe','Tide Bath Towel','Loomed Bed Cover','Folded Linen Runner'],storage:['Oakline Console','Raku Bedside Cabinet','Open Frame Shelf','Mori Media Unit','Tallboy Chest','Ledge Wall Shelf','Sora Sideboard','Cove Storage Bench','Stacked Drawer Unit','Pace Entry Cabinet']};
const base={seating:620,lighting:380,tabletop:440,textiles:310,storage:780};
const products=Object.entries(names).flatMap(([category,list])=>list.map((name,i)=>({id:`${category}-${i}`,category,name,price:base[category]+i*27,index:i, crop:`crop-${(i%5)+1}`, tone:i%2?'warm':'light'})));
let cart=JSON.parse(localStorage.getItem('boyue-cart')||'[]');
const $=s=>document.querySelector(s); const money=n=>`$${n.toLocaleString('en-US')}`;
function renderCategories(){ $('#category-grid').innerHTML=categories.slice(1).map(([key,label,crop])=>`<a class="category-card" href="#shop?category=${key}"><div class="image-crop ${crop}"></div><span class="label">${label} <small>↗</small></span></a>`).join(''); }
function renderFilters(active='all'){ $('#filters').innerHTML=categories.map(([key,label])=>`<a class="filter ${active===key?'active':''}" href="#shop${key==='all'?'':`?category=${key}`}" data-filter="${key}">${label}</a>`).join(''); }
function productImageStyle(p){if(p.id==='tabletop-5')return "background-image:url('./public/assets/contour-plinth.png');background-size:cover;background-position:center";return `background-image:url('./public/assets/${p.category}-products.png');background-size:500% 200%;background-position:${(p.index%5)*25}% ${p.index<5?0:100}%`}
function renderProducts(active='all'){const list=active==='all'?products:products.filter(p=>p.category===active);$('#shop-title').textContent=active==='all'?'All pieces':categories.find(c=>c[0]===active)?.[1];$('#product-grid').innerHTML=list.map((p,i)=>`<article class="product-card"><a href="#product=${p.id}"><div class="product-media"><div class="image-crop ${p.crop}" style="${productImageStyle(p)}"></div>${i<4?'<span class="badge">NEW ARRIVAL</span>':''}<button class="quick-add" data-add="${p.id}" aria-label="Add ${p.name}">+</button></div></a><div class="product-info"><div><strong>${p.name}</strong><p>${p.category[0].toUpperCase()+p.category.slice(1)} / ${String(p.index+1).padStart(2,'0')}</p></div><span class="price">${money(p.price)}</span></div></article>`).join('');renderFilters(active);}
function renderCart(){ $('#cart-count').textContent=cart.reduce((a,x)=>a+x.qty,0); const el=$('#cart-items'); if(!cart.length){el.innerHTML='<p class="empty-cart">Your bag is waiting for something with presence.<br><br>Explore the collection to begin.</p>';$('#cart-total').textContent='$0';return}el.innerHTML=cart.map(x=>`<div class="cart-line"><div class="image-crop" style="${productImageStyle(x)}"></div><div><h4>${x.name}</h4><p>${money(x.price)} · Qty ${x.qty}</p></div><button class="remove-line" data-remove="${x.id}">Remove</button></div>`).join('');$('#cart-total').textContent=money(cart.reduce((a,x)=>a+x.price*x.qty,0));}
function openCart(){renderCart();$('#cart-drawer').classList.add('open');$('.scrim').classList.add('open');$('#cart-drawer').setAttribute('aria-hidden','false')};function closeCart(){$('#cart-drawer').classList.remove('open');$('.scrim').classList.remove('open')};
function add(id){const p=products.find(x=>x.id===id), found=cart.find(x=>x.id===id);found?found.qty++:cart.push({...p,qty:1});localStorage.setItem('boyue-cart',JSON.stringify(cart));showToast(`${p.name} added to your bag`);openCart()}
const legal={payment:['Payment','We accept PayPal, Visa and major credit cards through our secure checkout provider. Payment is captured when your order is confirmed.'],returns:['Returns & refunds','Request a return within 14 days of delivery. Items must be unused, in original condition and safely packed. Refunds are issued to the original payment method after inspection. Custom or final-sale items are excluded.'],shipping:['Shipping policy','Orders are dispatched from our fulfilment partners within 2–4 business days. Delivery estimates and applicable duties are shown at checkout. You will receive tracking by email.'],tracking:['Order tracking','Use the tracking link in your dispatch email. For help, contact boyumaoyifazhan@outlook.com with your order number.'],cancellation:['Cancellation policy','You may cancel before dispatch by emailing us. Once an order has shipped, our returns policy applies.'],privacy:['Privacy policy','We use order and contact details only to provide the service, process payments, deliver purchases and improve our store. We do not sell personal information. Contact us for access or deletion requests.'],dmca:['DMCA','If you believe content on this site infringes your copyright, send a notice with the work, location, contact details and a good-faith statement to boyumaoyifazhan@outlook.com.'],terms:['Terms of Service','These Terms of Service govern use of the BOYUÉ store operated by 博裕貿易發展有限公司.']};
function modal(title,body){$('#modal-content').innerHTML=`<p class="eyebrow">BOYUÉ / INFORMATION</p><h2>${title}</h2>${body}`;$('#page-modal').classList.add('open');}
function openLegal(key){const [title,text]=legal[key]||legal.terms;let body=`<p>${text}</p><h3>Company details</h3><p>博裕貿易發展有限公司<br>381-383 Lockhart Road, Wan Chai District, Hong Kong Special Administrative Region<br>boyumaoyifazhan@outlook.com</p>`;if(key==='terms')body='<p>By using this site or placing an order, you agree to the following 17 sections.</p>'+['1. Acceptance','2. Eligibility','3. Accounts','4. Products and descriptions','5. Prices and availability','6. Orders and acceptance','7. Payment','8. Delivery','9. Returns and refunds','10. Cancellation','11. Intellectual property','12. User content','13. Prohibited use','14. Disclaimers','15. Limitation of liability','16. Indemnity','17. Governing law and contact'].map(x=>`<h3>${x}</h3><p>${text} This section is subject to applicable law and the company details shown below.</p>`).join('')+`<h3>Company details</h3><p>博裕貿易發展有限公司 · 381-383 Lockhart Road, Wan Chai District, Hong Kong Special Administrative Region · boyumaoyifazhan@outlook.com</p>`;modal(title,body)}
function route(){const hash=location.hash||'#home';if(hash.startsWith('#shop')){const q=hash.split('?category=')[1]||'all';renderProducts(q);document.querySelector('#shop').scrollIntoView()}else if(hash.startsWith('#product=')){const p=products.find(x=>x.id===hash.split('=')[1]);if(p)modal(p.name,`<p class="eyebrow">${p.category} / 01</p><p>Designed for daily rituals, made with honest materials and a quiet silhouette.</p><h3>${money(p.price)}</h3><button class="button button-dark" data-add="${p.id}">Add to cart <span>→</span></button>`)}else if(legal[hash.slice(1)])openLegal(hash.slice(1));else if(hash==='#admin')modal('Admin portal',`<div class="login-box"><p>Demo dashboard access for store management.</p><label>Email</label><input value="admin@boyuehome.com"><label>Password</label><input type="password" value="Boyue2026!" id="admin-password"><button class="button button-dark full" data-action="login">Sign in <span>→</span></button><p class="fine-print">Demo credentials are shown for this prototype only. Connect a real auth provider before production.</p></div>`)}
function showToast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
document.addEventListener('click',e=>{const addBtn=e.target.closest('[data-add]');if(addBtn){e.preventDefault();add(addBtn.dataset.add)}if(e.target.closest('[data-action="cart"]'))openCart();if(e.target.closest('[data-action="close-cart"]'))closeCart();if(e.target.closest('[data-action="close-modal"]'))$('#page-modal').classList.remove('open');const rem=e.target.closest('[data-remove]');if(rem){cart=cart.filter(x=>x.id!==rem.dataset.remove);localStorage.setItem('boyue-cart',JSON.stringify(cart));renderCart()}if(e.target.closest('[data-action="checkout"]')){if(!cart.length)return showToast('Your bag is empty');modal('Secure checkout',`<p>Your order is ready. Choose a payment method to continue.</p><div class="payment-options"><button class="button button-dark full">PayPal <span>→</span></button><button class="button button-dark full">Visa / Credit card <span>→</span></button></div><p class="fine-print">Payment processing is a demo in this prototype. Add your PayPal or card processor keys to activate live payments.</p>`)}if(e.target.closest('[data-action="login"]'))showToast('Demo dashboard signed in')});
renderCategories();renderProducts();renderCart();window.addEventListener('hashchange',route);route();
